data:
    image: busybox
    volumes:
        - ./:/var/www
        - /vendor
        - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
        - ~/.composer:/root/.composer
        - /tmpfs

nginx:
    image: nginx
    links:
        - php
    volumes_from:
        - data
    volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

php:
    build: docker/php
    working_dir: /var/www
    volumes_from:
        - data
    mem_limit: 2000000000
